endpoints:
  prometheus:
    enabled: true
    sensitive: false

micronaut:
  application:
    name: microhello
  metrics:
    enabled: true    
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M      

# tracing:
#   zipkin:
#     enabled: true
#     http:
#       url: http://localhost:9411
#     enabled: true
#     sampler:
#       probability: 1
